### ISSUE TITLE
Unable to transfer live call & unable to transfer a live call in conference

### ISSUE THREAD

**Issue by manoj2292** [plivo/plivo-node#61] opened 2017-11-11 07:32 UTC
I am trying to do two things using plivo transfer call api and plivo conference call api which are described below : 

1).When there is a live call from a to b answered, I am trying to transfer this call to c by using plivo call transfer call api but when I do so the call is getting hangup without giving any error. Though I have checked all data and action/callback url and I found it appropriate.

2).I tried the same thing using plivo conference call api but resulting in same issue.

I have referred https://github.com/plivo/plivo-node/issues/45, https://github.com/plivo/plivo-node/issues/46 but still not getting any solution.
 
So please if anyone have solution please inform.

**Comment by plivo-sdks** [comment] 2017-11-11 09:34
@manoj2292 Which version of the SDK are you using? Can you post the relevant code snippet here so we can reproduce this issue?

**Comment by manoj2292** [comment] 2017-11-11 13:28
@plivo-sdks I am using Browser SDK 2.0 for web and below are the steps which I am following : 

1).Incoming call to a leg

<Response>
   <Dial callerId="+15732605080" 
            callbackUrl="{{callbackURL}}" 
            action="{{actionUrl}}" 
            callbackMethod="POST" >
      <User>sip:sip1@phone.plivo.com</User>
      <User>sip:sip2@phone.plivo.com</User>
   </Dial>
</Response>

2). transfer an incoming  call to join the conference room : 

{
   call_uuid: 'ef4ecdaa-9a4a-4aba-b4ce-4eb89dbfd0e4'
   aleg_url: '{{conferenceJoinURL}}',
   aleg_method: 'POST'
   legs: 'aleg' 
}
And I get message from plivo as below: 
{ api_id: '3ea79c78-c6e1-11e7-920b-0600a1193e9b',
  call_uuids: [ '388b2526-c6e1-11e7-accc-c50f8090830b' ],
  message: 'transfer executed' }

**Note** : I have also tried this code with 'bleg' only and with 'both'

3). When plivo post data on urls that I have specified in transfer API (aleg/bleg/both),  I returns an XML from that {{conferenceJoinURL}} as below to join the call : 

<Response>
   <Conference enterSound="beep:2" startConferenceOnEnter="true" endConferenceOnExit="true">demo</Conference>
</Response>

But I can not able to join that calls in conference and calls are terminated.

Waiting for your reply,
Thanks.

**Comment by plivo-sdks** [comment] 2017-11-13 15:54
@manoj2292 Please raise a ticket here: support.plivo.com

Since this is not a Node.js SDK issue, we are closing this for now.

**Closed by plivo-sdks** 2017-11-13 15:54 UTC
